ChatExample/Controllers/ChatSessionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Codefirst_Models;

namespace ChatExample.Controllers
{
    public class ChatSessionsController : Controller
    {
        private Codefirst_Models.Models db = new Codefirst_Models.Models();

        // GET: ChatSessions
        public ActionResult Index()
        {
            return View(db.ChatSessions.ToList());
        }

        // GET: ChatSessions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChatSession chatSession = db.ChatSessions.Find(id);
            if (chatSession == null)
            {
                return HttpNotFound();
            }
            return View(chatSession);
        }

        // GET: ChatSessions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChatSessions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StartedAt")] ChatSession chatSession)
        {
            if (ModelState.IsValid)
            {
                db.ChatSessions.Add(chatSession);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(chatSession);
        }

        // GET: ChatSessions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChatSession chatSession = db.ChatSessions.Find(id);
            if (chatSession == null)
            {
                return HttpNotFound();
            }
            return View(chatSession);
        }

        // POST: ChatSessions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StartedAt")] ChatSession chatSession)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chatSession).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chatSession);
        }

        // GET: ChatSessions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChatSession chatSession = db.ChatSessions.Find(id);
            if (chatSession == null)
            {
                return HttpNotFound();
            }
            return View(chatSession);
        }

        // POST: ChatSessions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ChatSession chatSession = db.ChatSessions.Find(id);
            db.ChatSessions.Remove(chatSession);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public PartialViewResult SessionList(int? SelectedEelement)
        {
            ViewBag.SelectedEelement = SelectedEelement;
            return PartialView("_SessionList", db.ChatSessions.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChatExample/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Codefirst_Models;

namespace ChatExample.Controllers
{
    public class MessagesController : Controller
    {
        private Codefirst_Models.Models db = new Codefirst_Models.Models();

        // GET: Messages
        public ActionResult Index()
        {
            return View(db.Messages.ToList());
        }

        // GET: Messages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // GET: Messages/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Body,From,SentAt,ChatSessionId")] Message message)
        {
            if (ModelState.IsValid)
            {
                db.Messages.Add(message);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(message);
        }

        // GET: Messages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Body,From,SentAt,ChatSessionId")] Message message)
        {
            if (ModelState.IsValid)
            {
                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(message);
        }

        // GET: Messages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Message message = db.Messages.Find(id);
            db.Messages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MyMessages(int Id)
        {
            ViewBag.SessionId = Id;
            return View(db.Messages.Where(m => m.ChatSessionId == Id).ToList());
        }

        public JsonResult PostNewMessage(int ChatSessionId, string Email, string Body)
        {
            try
            {
                db.Messages.Add(new Message
                {
                    ChatSessionId = ChatSessionId,
                    Body = Body,
                    From = Email,
                    SentAt = DateTime.Now
                });
                db.SaveChanges();
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChatExample/Views/Messages/Create.cshtml
@model Codefirst_Models.Message

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SentAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SentAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SentAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChatSessionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ Html.RenderAction("SessionList", "ChatSessions", new {SelectedElement = -1});}
                @Html.ValidationMessageFor(model => model.ChatSessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChatExample/Views/Messages/Delete.cshtml
@model Codefirst_Models.Message

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SentAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SentAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChatSessionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChatSessionId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ChatExample/Views/Messages/Details.cshtml
@model Codefirst_Models.Message

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SentAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SentAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChatSessionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChatSessionId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ChatExample/Views/Messages/Edit.cshtml
@model Codefirst_Models.Message

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.From, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SentAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SentAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SentAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChatSessionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{ Html.RenderAction("SessionList","ChatSessions",new {SelectedEelement=Model.ChatSessionId});}
                @Html.ValidationMessageFor(model => model.ChatSessionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChatExample/Views/Messages/Index.cshtml
@model IEnumerable<Codefirst_Models.Message>

@{
    ViewBag.Title = "Index";
    Codefirst_Models.Models db = new Codefirst_Models.Models();
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.From)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SentAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ChatSessionId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.From)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SentAt)
        </td>
        <td>
            @db.ChatSessions.Where(m=>m.Id==item.ChatSessionId).FirstOrDefault().StartedAt.ToString("dd-MMMM-yyyy")
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ChatExample/Views/Messages/MyMessages.cshtml
@using Codefirst_Models;
@model List<Message>
@{
    ViewBag.Title = "Welcome To Chat";
    ViewBag.MetaDescription = "Hello it's a free product which developed by Advanced Developer.";
    ViewBag.MetaKeywords = "Programming,Chat,SignalR,MVC,Course,Csharp,OOP,Asp.net,Web";
}
<h1>Chat Session</h1>
@{
    <div class="Messages">
        @foreach (var message in Model)
        {
            <div class="row message">
                <div class="col col-md-3 col-lg-3 col-sm-12 col-xs-12">
                    @message.From
                </div>
                <div class="col col-md-9 col-lg-9 col-sm-12 col-xs-12">
                    @message.Body   (@message.SentAt)
                </div>
            </div>
        }
    </div>
}
<div class="row">
    <label class="col col-md-3 col-lg-3 col-sm-12 col-xs-12">Message:</label>
    <input type="text" id="Message_Txt" placeholder="Message" class="form-control col col-md-6 col-lg-6 col-sm-12 col-xs-12" />
    <input type="text" id="MyEmail_Txt" placeholder="Email" class="form-control col col-md-3 col-lg-3 col-sm-12 col-xs-12" />
    <input type="button" onclick="SendMessage()" value="Send" class="btn btn-success" />
</div>
@section scripts {
<script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
<script src="~/signalr/hubs"></script>
}

<script>
    function SendMessage() {
        var dataForm = {};
        dataForm.Message = $('#Message_Txt').val();
        dataForm.Email = $('#MyEmail_Txt').val();
        dataForm.SessionId = '@ViewBag.SessionId';


        var ajaxoptions = {};
        ajaxoptions.url = "@Url.Action("PostNewMessage")";
        ajaxoptions.data = { Email: dataForm.Email, Body: dataForm.Message, ChatSessionId: dataForm.SessionId };
        ajaxoptions.success = function (result) {
            if (result) {
                PostAllSessions(dataForm, 'done');
                //RenderNewMessage(dataForm.Email, dataForm.Message, 'done');
            } else {
                //RenderNewMessage(dataForm.Email, dataForm.Message, 'faild');
                PostAllSessions(dataForm, 'faild');
            }
        }
        $.ajax(ajaxoptions);
    }
    function RenderNewMessage(Email,Message, status) {
        var StyleClass = 'Success';
        if (status !== 'done') {
            StyleClass = 'Faild';
        }
        var NewMessage = '<div class="row message ' + StyleClass + '">' +
            '<div class="col col-md-3 col-lg-3 col-sm-12 col-xs-12">' +
                Email +
            '</div>' +
            '<div class="col col-md-9 col-lg-9 col-sm-12 col-xs-12">' +
                Message +
            '</div>' +
        '</div>';

        $(NewMessage).css('display', 'none');
        $('.Messages').append($(NewMessage).fadeIn(500));

    }
    function PostAllSessions(dataForm, status) {
        var chat = $.connection.chatHub;
        // Create a function that the hub can call back to display messages.
        chat.client.addNewMessageToPage = function (email,message, status) {
            RenderNewMessage(email, message, status);
        };
        $.connection.hub.start().done(function () {
            chat.server.send(dataForm.Email,dataForm.Message,status);
        });
    }
</script>